-- AlterTable
ALTER TABLE `user` ADD COLUMN `biography` VARCHAR(191) NULL,
    ADD COLUMN `birthDate` VARCHAR(191) NULL,
    ADD COLUMN `location` VARCHAR(191) NULL,
    ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'Online';
